name: 04-TruffleHog-Security-Scan
on:
  #Only manual trigger for now
  # TODO analyse what to enable    
  #pull_request:
    #    branches:
    #        - main
    #        - develop
    workflow_dispatch:
jobs:
  trufflehog_scan:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@v3.84.0
      with:
        extra_args: --only-verified
