name: 04-TruffleHog-Security-Scan
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  trufflehog_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --only-verified
